services:
  agent-zero:
    container_name: agent-zero
    build:
      context: ../..
      dockerfile: DockerfileLocal
      args:
        CACHE_DATE: ${CACHE_DATE:-dev}
    image: agent-zero-local
    volumes:
      - ../..:/a0
    ports:
      - "50080:80"
